server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aliakbar-dev/spring-cloudconfig-ansaralhojat
          search-paths:
            - station*
  security:
    user:
      name: pluralsight
      password: pluralsight

encrypt:
  key: pluralsight
